---

- name: install dependecies
  package:
    name: "{{ dht_to_influx_dependencies }}"
    state: present
  when:
    - dht_to_influx_dependencies | default([]) | count > 0

- name: python support
  block:
    - name: create requirements.txt
      template:
        src: requirements.txt.j2
        dest: /tmp/dht_to_influx-requirements.txt
        mode: 0660

    - name: ensure python bindings for dht_to_influx packages 1st
      pip:
        requirements: /tmp/dht_to_influx-requirements.txt
        state: present
        # extra_args: "--force-pi"
      register: pip_install
      ignore_errors: true
      no_log: true

  when:
    - dht_to_influx_python_packages is defined
    - dht_to_influx_python_packages | length > 0

- name: clone git sources to /opt/dht_to_influx
  git:
    repo: "{{ dht_to_influx_git.repository }}"
    version: "{{ dht_to_influx_git.version | default('master') }}"
    dest: /opt/dht_to_influx/
    depth: 1
    update: true
    force: true

- name: create dht_to_influx directory
  become: true
  file:
    state: directory
    owner: "{{ dht_to_influx_user }}"
    group: "{{ dht_to_influx_group }}"
    mode: 0755
    path: /usr/local/bin/dht_to_influx

- name: copy files into system
  become: true
  copy:
    src: "/opt/dht_to_influx/{{ item }}"
    dest: /usr/local/bin/dht_to_influx/
    owner: "{{ dht_to_influx_user }}"
    group: "{{ dht_to_influx_group }}"
    mode: 0755
    remote_src: true
  loop:
    - bin

- name: create link to working directory
  file:
    state: link
    src: /usr/local/bin/dht_to_influx/bin/dht_to_influx.py
    dest: /bin/dht_to_influx.py
    force: true
    follow: false
  notify:
    - restart service

- name: create service config
  become: true
  template:
    src: etc/dht_sensors.rc.j2
    dest: /etc/dht_sensors.rc
    mode: 0644

- name: create systemd unit file
  become: true
  template:
    src: etc/init/systemd/dht-push-to-influx.service.j2
    dest: /lib/systemd/system/dht-push-to-influx.service
    mode: 0644
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: ensure service is enabled on boot
  become: true
  service:
    name: dht-push-to-influx
    enabled: true
    state: started

...
