---

- name: systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: restart service
  become: true
  ansible.builtin.service:
    name: dht-push-to-influx
    state: restarted

...
